#
# Configuration File
#

# Enable additional diagnostics
verbose: true
profile: true

# Information for compile
exclude:
  - "Gemfile"
  - "CNAME"
  - "LICENSE"
  - "README.md"
  - "DEVELOPMENT.md"
  - "*.js"
  - "*.json"
  - "assets/images/favicon/*.md"
  - "assets/images/favicon/*.html"
  - "assets/images/favicon/*.xml"

# Plugins
plugins:
  - jekyll-sitemap

# Sass configuration
sass:
  sass_dir: _scss

collections_dir: collections
collections:
  videos:
    output: true

excerpt_separator: <!--excerpt-->

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: https://binauralbeatbank.com

assets_path:  assets
css_path:     assets/css
images_path:  assets/images

##
## HEADER INFORMATION
##

# This is the site title
title: Binaural Beat Bank
# This is the site description - must be between 25 and 160 characters for Bing SEO
description: >
  Collection of binaural beat sound tracks to help synchronize brain hemispheres
  and train the brain to encourage brain states (relax, creative, focus).

# Website language
lang: en-US
# Header Title
header-title: Binaural Beat Bank
# Header Tagline
header-tagline1: Binaural Beat Collection
header-tagline2: Train Your Brain Waves

# The general contact default email address
email: hello@binauralbeatbank.com

##
## Global Social Links
##
facebook: https://www.facebook.com/BinauralBeatBank/
instagram: https://www.instagram.com/BinauralBeatBank/
tiktok: https://www.tiktok.com/@BinauralBeatBank
youtube: https://www.youtube.com/@BinauralBeatBank

##
## Global Images
##
facebook-image: icons/facebook.svg
instagram-image: icons/instagram.svg
twitterx-image: icons/twitterx.svg
tiktok-image: icons/tiktok.svg
youtube-image: icons/youtube.svg
linkedin-image: icons/linkedin.svg
email-image: icons/email.svg
pinterest-image: icons/pinterest.svg
shop-image: icons/shop.svg
amazon-image: icons/amazon.svg

##
## Footer
##
footer-description: Find us on social media.
footer-copyright-text: Cardillo's Creations, LLC
footer-copyright-year: 2023
